version: 2
updates:
- package-ecosystem: composer
  directory: "/src"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: npm
  directory: "/src"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 10
  target-branch: develop
