name: Develop docker test
on: [ push, pull_request ]

env:
    REGISTRY: docker.pkg.github.com/hose1021/devhub
    REGISTRY_HOST: docker.pkg.github.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache composer
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
      
      - name: Cache frontend yarn
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          
      - name: Docker login
        uses: azure/docker-login@v1
        with:
           login-server: ${{ env.REGISTRY_HOST }}
           username: hose1021
           password: ${{ github.token }}
      
      - name: Docker pull
        run: make docker-pull
        
      - name: Docker build
        run: make docker-build
        
      - name: Composer install
        run: make composer-install
        
      - name: Yarn install
        run: make yarn-install
        
      - name: Docker up
        run: make docker-up
        
      - name: Copy .env
        run: make env
        
      - name: Generate key
        run: make key
        
      - name: Storage link create
        run: make storage
      
      - name: Generate passport
        run: make passport
