name: Deployment Workflow
on: [push, pull_request]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to git repo
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url --add --push origin ssh://h75062@h75062.hostde31.fornex.host:20022/home/h75062/public_html
          git add .
          git commit -m "Push to cPanel"
          git push https://${{ secrets.GITHUB_TOKEN }}@h75062@h75062.hostde31.fornex.host/h75062/devhub.git -f
