name: Deployment Workflow
on: [push, pull_request]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - name: Push to git repo
        run: |
          git remote add deploy ssh://h75062@h75062.hostde31.fornex.host:20022/home/h75062/public_html
          git add .
          git commit -m "Push to cPanel"
          git push -u deploy master
